#!/usr/bin/env tsx
/**
 * Renders the worker schedule for whichever thing is doing the scheduling.
 *
 *   npm run schedule            print the crontab and the workflow
 *   npm run schedule -- --write write them into deploy/
 *
 * ── Why the schedule is not in vercel.json ─────────────────────────────────
 *
 * Vercel Hobby allows **one cron run per day**, and refuses the deploy outright if any
 * expression asks for more:
 *
 *     Hobby accounts are limited to daily cron jobs. This cron expression
 *     (*\/15 * * * *) would run more than once per day.
 *
 * The intake worker is supposed to run every fifteen minutes and the mirror every hour,
 * so daily is not a smaller version of the design — it is a different product. Upgrading
 * Vercel to Pro would fix it for about twenty dollars a month; so would the VPS that is
 * already paid for. This renders both, and a GitHub Actions workflow as a third option,
 * because the choice is a budget decision and not a technical one.
 *
 * ── One source, three renderings ───────────────────────────────────────────
 *
 * The schedule lives in `WORKERS` and nowhere else. Every target here is generated from
 * it, and a test asserts the generated files still cover every worker — which is the same
 * guarantee the `vercel.json` test gave, now that vercel.json no longer carries it.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { WORKERS, WORKER_NAMES } from '../src/workers'
import { speaker } from '../speaker.config'

const BASE = process.env.NEXTAUTH_URL ?? 'https://louis-v3.vercel.app'

/**
 * A crontab for the VPS.
 *
 * `--fail` so a 5xx is a non-zero exit and cron's own mail catches it; `--max-time` so a
 * hung request cannot pile up runs on top of each other.
 */
export function crontab(base = BASE, timezone = speaker.timezone): string {
  const lines = [
    '# Louis workers. Generated by `npm run schedule` — edit the registry, not this file.',
    '#',
    '# Install:  crontab -l > /tmp/cur && cat deploy/louis.crontab >> /tmp/cur && crontab /tmp/cur',
    '# Requires: CRON_SECRET filled in below, matching the value set on the app.',
    '#',
    '# CRON_TZ matters more than it looks. These are human times, not machine times:',
    '# 7am is when the morning digest lands on somebody\'s phone, and 5:30 is when the QA',
    '# sweep finishes before anyone is up. A VPS is almost always on UTC, so without this',
    '# line the digest arrives at midnight Pacific and the reply-SLA sweep runs through',
    "# the night and sleeps through the working day. It is the speaker's timezone because",
    '# the people reading the output are in it.',
    '',
    'SHELL=/bin/bash',
    `CRON_TZ=${timezone}`,
    'CRON_SECRET=replace-me',
    '',
  ]
  for (const name of WORKER_NAMES) {
    const w = WORKERS[name]!
    lines.push(`# ${w.title}${w.critical ? ' (critical: runs even at the AI cap)' : ''}`)
    lines.push(
      `${w.schedule} curl -sS --fail --max-time 280 -H "Authorization: Bearer $CRON_SECRET" ` +
        `${base}/api/cron/${name} > /dev/null`,
    )
    lines.push('')
  }
  return lines.join('\n')
}

/** A GitHub Actions workflow, for when there is no VPS and no Vercel Pro. */
export function workflow(base = BASE): string {
  const schedules = WORKER_NAMES.map((n) => `    - cron: '${WORKERS[n]!.schedule}'`).join('\n')
  return `# Generated by \`npm run schedule\`. Edit the worker registry, not this file.
#
# GitHub's scheduled workflows are best-effort and can be delayed by several minutes under
# load, which is fine for a sweep and wrong for anything that has to happen on the minute.
# Needs two repository secrets: LOUIS_BASE_URL and CRON_SECRET.
name: Louis workers

on:
  schedule:
${schedules}
  workflow_dispatch:
    inputs:
      worker:
        description: Run one worker now
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      # One failing worker must not cancel the others.
      fail-fast: false
      matrix:
        worker: [${WORKER_NAMES.join(', ')}]
    steps:
      - name: \${{ matrix.worker }}
        run: |
          curl -sS --fail --max-time 280 \\
            -H "Authorization: Bearer \${{ secrets.CRON_SECRET }}" \\
            "\${{ secrets.LOUIS_BASE_URL }}/api/cron/\${{ matrix.worker }}"
`
}

/**
 * What `vercel.json` could carry on a Hobby plan: nothing more than daily.
 *
 * Printed rather than written, because a daily intake sweep looks like the system working
 * while quietly being fifteen-minute promises delivered once a night.
 */
export function vercelHobbyNote(): string {
  const tooOften = WORKER_NAMES.filter((n) => !/^\d+ \d+ \* \* \*$/.test(WORKERS[n]!.schedule))
  return tooOften.length === 0
    ? 'Every schedule is daily; vercel.json could carry them on Hobby.'
    : `Hobby cannot run: ${tooOften.map((n) => `${n} (${WORKERS[n]!.schedule})`).join(', ')}.`
}

function main() {
  const write = process.argv.includes('--write')
  const cron = crontab()
  const gha = workflow()

  if (write) {
    mkdirSync('deploy', { recursive: true })
    writeFileSync('deploy/louis.crontab', cron)
    // Written to deploy/ rather than .github/workflows/ on purpose. It is a template for
    // a scheduler nobody has chosen yet, and a file in .github/workflows is a *running*
    // workflow — committing one needs a token with `workflow` scope, and enabling a
    // scheduler should be a decision somebody makes rather than a side effect of a push.
    writeFileSync('deploy/workers.github.yml', gha)
    console.log('Wrote deploy/louis.crontab and deploy/workers.github.yml')
    console.log('To use the GitHub option: move the second into .github/workflows/.')
  } else {
    console.log(cron)
    console.log('─'.repeat(72))
    console.log(gha)
  }
  console.log(`\n${vercelHobbyNote()}`)
}

if (process.argv[1]?.endsWith('generate-schedule.ts')) main()
